apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
spec:
  #  type: NodePort
  ports:
    - name: "app-service"
      port: 5000
      targetPort: 10001
  #      nodePort: 30010
  selector:
    app: app
    version: rc-origin

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: app-$Namespace$.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 5000