apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app-rc-origin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: rc-origin
  template:
    metadata:
      labels:
        app: app
        version: rc-origin
    spec:
      containers:
        - image: registry.cn-shanghai.aliyuncs.com/ky-dev/spring-boot-k8s
          name: spring-boot-k8s
          ports:
            - containerPort: 10001
              name: app
          resources:
            limits:
              memory: 500Mi
              cpu: 50m
